### ISSUE TITLE
Not really an issue; had a question

### ISSUE THREAD

**Issue by rish-16** [tlkh/dl-project-xray#2]
Can I know what you trained the model on? Hardware-wise, that is.

Also, how did you tackle the class imbalance problem? Were there any techniques you used?

Thanks!

**Comment by tlkh** [comment]
Trained on 1 V100. Smaller dataset was a bigger issue. 
We didn't solve the class imbalance problem. Obviously the model we got here is actually piss-poor for any real world usage. This is a 2 week school project.

**Comment by rish-16** [comment]
Oh lol alright. Good luck with it, though XD
